server:
  port: 9005
spring:
  application:
    name: ribbon-consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/,http://localhost:9004/eureka/
  instance:
    hostname: localhost
    preferIpAddress: true
    instance-id: ${eureka.instance.hostname}:${server.port}

#Actuator配置
info:
  head: head
  body: body
management:
  endpoints:
    web:
      exposure:
        #加载所有的端点，默认只加载了info、health
        include: '*'
  endpoint:
    health:
      show-details: always
    #可以关闭指定的端点
    shutdown:
      enabled: false