spring:
  application:
    name: feign-consumer
server:
  port: 9010

#注册中心配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/,http://localhost:9004/eureka/

#全局ribbon配置
ribbon:
  ConnectTimeout: 500
  ReadTimeout: 5000

#指定服务ribbon配置
#serivce-user:
#  ribbon:
#    ConnectTimeout: 500